server:
  port: 9020
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: wisekit
    password: wisekit
    driver-class-name: oracle.jdbc.driver.OracleDriver
  thymeleaf:
    cache: false
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace